[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 302
  force = false
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  force = false
