[build]
  publish = "_site"
  command = "eleventy"
  functions = "./functions"

# Redirect old style locale URLs to new ones
[[redirects]]
  from = "/de-DE/*"
  to = "/de/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/es-ES/*"
  to = "/es-es/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/es-LA/*"
  to = "/es-la/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/fr-CA/*"
  to = "/fr-ca/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/fr-FR/*"
  to = "/fr-fr/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/it-IT/*"
  to = "/it/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ja-JP/*"
  to = "/ja/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ko-KR/*"
  to = "/ko/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/nl-NL/*"
  to = "/nl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pl-PL/*"
  to = "/pl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pt-BR/*"
  to = "/pt-br/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pt-PT/*"
  to = "/pt-pt/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ru-RU/*"
  to = "/ru/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/zh-CN/*"
  to = "/zh-cn/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/zh-TW/*"
  to = "/zh-tw/:splat"
  status = 302
  force = false

# Leave it last as the default redirect
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/redirect/:splat"
  status = 302
  force = false
