[build]
  publish = "_site"
  command = "eleventy"


# Redirect old style locale URLs to new ones
[[redirects]]
  from = "/de-DE/*"
  to = "/de/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/es-ES/*"
  to = "/es/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/es-LA/*"
  to = "/es/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/fr-CA/*"
  to = "/fr/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/fr-FR/*"
  to = "/fr/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/it-IT/*"
  to = "/it/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ja-JP/*"
  to = "/ja/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ko-KR/*"
  to = "/ko/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/nl-NL/*"
  to = "/nl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pl-PL/*"
  to = "/pl/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pt-BR/*"
  to = "/pt/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/pt-PT/*"
  to = "/pt/:splat"
  status = 302
  force = false

[[redirects]]
  from = "/ru-RU/*"
  to = "/ru/:splat"
  status = 302
  force = false


# Rediret based on Accept-Language

[[redirects]]
  from = "/*"
  to = "/de/:splat"
  status = 302
  force = false
  conditions = {Language = ["de"]}

[[redirects]]
  from = "/*"
  to = "/es/:splat"
  status = 302
  force = false
  conditions = {Language = ["es"]}

[[redirects]]
  from = "/*"
  to = "/fr/:splat"
  status = 302
  force = false
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/*"
  to = "/it/:splat"
  status = 302
  force = false
  conditions = {Language = ["it"]}

[[redirects]]
  from = "/*"
  to = "/ja/:splat"
  status = 302
  force = false
  conditions = {Language = ["ja"]}

[[redirects]]
  from = "/*"
  to = "/ko/:splat"
  status = 302
  force = false
  conditions = {Language = ["ko"]}

[[redirects]]
  from = "/*"
  to = "/nl/:splat"
  status = 302
  force = false
  conditions = {Language = ["nl"]}

[[redirects]]
  from = "/*"
  to = "/pl/:splat"
  status = 302
  force = false
  conditions = {Language = ["pl"]}

[[redirects]]
  from = "/*"
  to = "/pt/:splat"
  status = 302
  force = false
  conditions = {Language = ["pt"]}

[[redirects]]
  from = "/*"
  to = "/ru/:splat"
  status = 302
  force = false
  conditions = {Language = ["ru"]}

[[redirects]]
  from = "/*"
  to = "/zh-cn/:splat"
  status = 302
  force = false
  conditions = {Language = ["zh-CN"]}

[[redirects]]
  from = "/*"
  to = "/zh/:splat"
  status = 302
  force = false
  conditions = {Language = ["zh-TW"]}

# Leave it last as the default redirect
[[redirects]]
  from = "/*"
  to = "/en/:splat"
  status = 302
  force = false
