[build]
  publish = "_site"
  command = "eleventy"

[[redirects]]
  from = "/"
  to = "/en/about/"
  status = 302
  force = false


[[redirects]]
  from = "/"
  to = "/de/about/"
  status = 302
  force = false
  conditions = {Language = ["de"]}
